ALTER TABLE public.profiles
DROP COLUMN cpf,
DROP COLUMN phone_number,
DROP COLUMN address_street,
DROP COLUMN address_number,
DROP COLUMN address_complement,
DROP COLUMN address_district,
DROP COLUMN address_postal_code,
DROP COLUMN address_city,
DROP COLUMN address_state;